[pytest]
minversion = 7.0
addopts = 
    --strict-markers
    --maxfail=3
    --tb=short
    --disable-warnings
    --cov=app
    --cov-report=term-missing
testpaths = app/tests
python_files = test_*.py
env = PYTHONPATH=.

# Custom markers
markers =
    integration: marks tests as integration tests (slow, DB, API calls)
    unit: marks tests as unit tests (fast, isolated)
